name: Update Stats

on:
  schedule:
    - cron: "0 19 * * *"   # Har kuni 00:00 Toshkent vaqti (19:00 UTC)
  workflow_dispatch:       # Qo'lda ham ishga tushirish mumkin
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py
